{% set version = "5.0.0" %}

package:
  name: smmap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap/smmap-{{ version }}.tar.gz
  sha256: c840e62059cd3be204b0c9c9f74be2c09d5648eddd4580d9314c3ecde0b30936

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pure git implementation of a sliding window memory map manager.

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
